### ISSUE TITLE
Problems to resolve files for 0.90.0-RC1

### ISSUE THREAD

**Issue by StefanOltmann** [pdvrieze/xmlutil#209]
I see why you made it a release candidate. ;)

Dependency resolution fails here:
```
Execution failed for task ':transformPosixMainCInteropDependenciesMetadataForIde'.
> Could not resolve all files for configuration ':iosArm64CompilationDependenciesMetadata'.
   > Could not find io.github.pdvrieze.xmlutil:compat-iosarm64:0.90.0-RC1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/io/github/pdvrieze/xmlutil/compat-iosarm64/0.90.0-RC1/compat-iosarm64-0.90.0-RC1.pom
       - https://repo.maven.apache.org/maven2/io/github/pdvrieze/xmlutil/compat-iosarm64/0.90.0-RC1/compat-iosarm64-0.90.0-RC1.pom
     Required by:
         project : > io.github.pdvrieze.xmlutil:core:0.90.0-RC1
```

The mentioned path `https://repo.maven.apache.org/maven2/io/github/pdvrieze/xmlutil/compat-iosarm64/0.90.0-RC1/compat-iosarm64-0.90.0-RC1.pom` does not exist, but `https://repo.maven.apache.org/maven2/io/github/pdvrieze/xmlutil/compat-iosArm64/0.90.0-RC1/compat-iosArm64-0.90.0-RC1.pom` with uppercase `A` in `iosArm64` does.

Reproducer branch: https://github.com/Ashampoo/xmpcore/tree/kotlin2

**Comment by pdvrieze** [comment]
That is very very strange indeed. I've had a look at my local repository. The same issue seems to happen with all native targets (the archive names for older versions have lower case names). I'll have to dig into the kotlin multiplatform plugin to figure out what is going on there.

**Comment by pdvrieze** [comment]
I've figured out something. I've been renaming artifactIds and somehow those renames were not incorporated in the pom/dependency generation.

**Comment by pdvrieze** [comment]
I've just pushed a snapshot. It "fixes" these names, but I'm not sure it works throughout.

**Comment by pdvrieze** [comment]
I've just pushed a tag for RC2. It should have fixed this (I created a test project that resolves correctly for me now). It should be making its way through mavencentral now.

**Comment by StefanOltmann** [comment]
Unfortunately https://github.com/Ashampoo/xmpcore/tree/kotlin2 still fails for me.

Now it's looking for an artifact `io.github.pdvrieze.xmlutil:base-iosarm64:0.90.0-RC2` which would be available at https://repo.maven.apache.org/maven2/io/github/pdvrieze/xmlutil/base-iosarm64/0.90.0-RC2/base-iosarm64-0.90.0-RC2.pom 

In the folder I don't see a `base` prefix. I only see artifacts starting with `compat-` and `core-`.

**Comment by pdvrieze** [comment]
Thanks for your feedback. It seems that this is something to do with partially building on different platforms (and the renames not working there). I'm trying a snapshot built on macos only.

**Comment by pdvrieze** [comment]
Thanks to the reproducer branch I believe I've resolved it. Three is a problem with artefact renames when components refer to each other (and I have renames to maintain compatibility even though the structure is changed). RC3 should be out soon.

**Comment by StefanOltmann** [comment]
@pdvrieze Thanks. I can confirm that RC3 works for me.
